backend:
  name: git-gateway
  branch: main

media_folder: "/"
public_folder: "/"

site_url: "https://thelifeexperiencebandbd.netlify.app"

collections:
  - name: "band_data"
    label: "Band Management"
    files:
      - file: "data/members.json"
        label: "Band Members List"
        name: "members_list"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Bio", name: "bio", widget: "string" }
